# Generated by Django 6.0.2 on 2026-02-19 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_city', models.CharField(db_index=True, max_length=100)),
                ('to_city', models.CharField(db_index=True, max_length=100)),
                ('bus_name', models.CharField(max_length=200)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('delayed', 'Delayed'), ('stopped', 'Stopped'), ('maintenance', 'Maintenance'), ('cancelled', 'Cancelled')], default='running', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bus_routes',
                'ordering': ['from_city', 'to_city', 'departure_time'],
                'indexes': [models.Index(fields=['from_city', 'to_city'], name='bus_routes_from_ci_9a1c90_idx'), models.Index(fields=['status'], name='bus_routes_status_f5b0ca_idx'), models.Index(fields=['departure_time'], name='bus_routes_departu_838639_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusLocationHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='bus_models.busroute')),
            ],
            options={
                'db_table': 'bus_location_history',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['bus', '-timestamp'], name='bus_locatio_bus_id_11a0ea_idx')],
            },
        ),
    ]
