# Generated by Django 6.0.2 on 2026-02-19 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComplaint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(db_index=True, max_length=15)),
                ('complaint_type', models.CharField(choices=[('service', 'Service Issue'), ('behavior', 'Staff Behavior'), ('bus_condition', 'Bus Condition'), ('safety', 'Safety Concern'), ('cleanliness', 'Cleanliness Issue'), ('delay', 'Delay Issue'), ('lost_found', 'Lost & Found'), ('other', 'Other Complaint')], default='other', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('bus_number', models.CharField(blank=True, max_length=20, null=True)),
                ('route', models.CharField(blank=True, max_length=100, null=True)),
                ('incident_date', models.DateTimeField(blank=True, null=True)),
                ('incident_location', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('filed', 'Filed'), ('investigating', 'Investigating'), ('action_taken', 'Action Taken'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='filed', max_length=20)),
                ('resolution_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_complaints', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_complaints',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='user_compla_user_id_fd7a6a_idx'), models.Index(fields=['status', 'created_at'], name='user_compla_status_150671_idx'), models.Index(fields=['complaint_type', 'severity'], name='user_compla_complai_b98b95_idx'), models.Index(fields=['mobile_number'], name='user_compla_mobile__63acac_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(db_index=True, max_length=15)),
                ('query_type', models.CharField(choices=[('general', 'General Query'), ('route', 'Route Information'), ('timing', 'Timing Query'), ('booking', 'Booking Issue'), ('payment', 'Payment Issue'), ('technical', 'Technical Issue'), ('other', 'Other')], default='general', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_response', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_queries', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_queries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='user_querie_user_id_2bbfd8_idx'), models.Index(fields=['status', 'created_at'], name='user_querie_status_d132cf_idx'), models.Index(fields=['mobile_number'], name='user_querie_mobile__968dc5_idx')],
            },
        ),
    ]
